name: test

on:
  workflow_dispatch:
    inputs:
      test-ref:
        description: 'Ref (tag/branch/SHA)'
        default: 'main'
  pull_request:
    branches:
      - 'main'

run-name: Run acceptance tests::Ref=${{ github.event_name == 'pull_request' && format('PR {0}', github.ref_name) || inputs.test-ref }}

env:
  TIMEOUT_LENGTH: 120000

jobs:
  run_acceptance_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout pass-acceptance-testing
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Use Node.js 24
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
            node-version: '24'
            cache: 'yarn'

      - name: Run acceptance tests
        uses: ./.github/actions/acceptance-test
        with:
          timeouts: $TIMEOUT_LENGTH
          test-ref: ${{ github.event_name == 'pull_request' && '' || inputs.test-ref }}
