name: test

on:
  workflow_dispatch:
    inputs:
      test-ref:
        description: 'Ref (tag/branch/SHA)'
        default: 'main'
  pull_request:
    branches:
      - 'main'

run-name: Run acceptance tests::Ref=${{ github.event_name == 'pull_request' && 'PR ' + github.ref_name || inputs.test-ref }}

env:
  TIMEOUT_LENGTH: 120000

jobs:
  run_acceptance_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout pass-acceptance-testing
        uses: actions/checkout@v3

      - name: Run acceptance tests
        uses: ./.github/actions/acceptance-test
        with:
          timeouts: $TIMEOUT_LENGTH
          test-ref: ${{ github.event_name == 'pull_request' && '' || inputs.test-ref }}
